package org.shadowrunrussia2020.android.di

import org.shadowrunrussia2020.android.common.di.ApplicationSingletonScope
import org.shadowrunrussia2020.android.main.ApplicationSingletonScopeMainDependency

interface IApplicationSingletonDi: ApplicationSingletonScope , ApplicationSingletonScopeMainDependency